#[allow(dead_code)]
#[derive(Clone, Debug)]
pub enum CatCommand {
    StartBlock,
    CloseBlock,
    CreateInteger(i64),
    CreateString(String),
    CreateCommand(Box<CatCommand>),
    Write,
    WriteLine,
    ReadLine,
    Add,
    Multiply,
    Execute,
    ExecuteScoped,
    Map,
    ForEach,
    Repeat,
    Split,
    ToInteger,
    Range,
    Duplicate,
    DuplicateSecond,
    Drop,
    Rotate(usize),
    PushSide,
    PopSide,
    ConsumeSide,
    Join,
    PushVariable(char),
    PopVariable(char, bool),
}
